spring.application.name=LeetCode

# ? JDBC URL format for PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d2939jjuibrs73e5kf3g-a.oregon-postgres.render.com:5432/leetcode_db_ty1l
spring.datasource.username=leetcode_db_ty1l_user
spring.datasource.password=gLwn9ztQrLqvec90cfOhcRyobTqqxpco

# Optional - update JPA settings
spring.jpa.hibernate.ddl-auto=update

# Optional Redis - disable for now
spring.cache.type=none
